
[colors.bright]
black = "#2e3436"
blue = "#729fcf"
cyan = "#34e2e2"
green = "#8ae234"
magenta = "#ad7fa8"
red = "#ef2929"
white = "#eeeeec"
yellow = "#fce94f"

[colors.normal]
black = "#2e3436"
blue = "#3465a4"
cyan = "#06989a"
green = "#73d216"
magenta = "#75507b"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#edd400"

[colors.primary]
background = "#000000"
foreground = "#a9b1d6"

[font]
size = 16

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "buttonless"
opacity = 0.7

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
